#!/usr/bin/env bash
# Ensures a Vercel project exists for this repo and resolves its id.
#
# Lazy infra provisioning: repos generated by deploy-orchestrator ship with an
# EMPTY VERCEL_PROJECT_ID variable — the first deploy creates the project
# (named after the repo, no framework preset so the root Dockerfile/Container
# preset is used) and back-fills the repo variable for subsequent runs.
#
# Env in:  VERCEL_TOKEN      (required — Vercel API token)
#          VERCEL_ORG_ID     (required — Vercel team/org id)
#          REPO              (required — project name, usually the repo name)
#          VERCEL_PROJECT_ID (optional — skips resolution when set)
#          GITHUB_REPOSITORY (optional — for the variable back-fill)
#          GH_ADMIN_TOKEN    (optional — token with variables write; without it
#                             the id is re-resolved on every run)
# Env out: project_id=<id> appended to $GITHUB_OUTPUT
set -euo pipefail

: "${VERCEL_TOKEN:?VERCEL_TOKEN secret is required}"
: "${VERCEL_ORG_ID:?VERCEL_ORG_ID variable is required}"
: "${REPO:?REPO is required}"

vapi() { # <method> <path> [json-body]
  local args=(-X "$1" -H "Authorization: Bearer $VERCEL_TOKEN")
  [ -n "${3:-}" ] && args+=(-H 'Content-Type: application/json' -d "$3")
  curl -sf "${args[@]}" "https://api.vercel.com$2?teamId=$VERCEL_ORG_ID"
}

if [ -z "${VERCEL_PROJECT_ID:-}" ]; then
  if ! vapi GET "/v9/projects/$REPO" > /dev/null 2>&1; then
    echo "Creating Vercel project '$REPO'"
    vapi POST "/v11/projects" "{\"name\":\"$REPO\",\"framework\":null}" > /dev/null \
      || { echo "::error::could not create Vercel project '$REPO'"; exit 1; }
  fi
  VERCEL_PROJECT_ID=$(vapi GET "/v9/projects/$REPO" | jq -r '.id')
  [ -n "$VERCEL_PROJECT_ID" ] && [ "$VERCEL_PROJECT_ID" != "null" ] \
    || { echo "::error::could not resolve Vercel project id for '$REPO'"; exit 1; }
  echo "Resolved Vercel project '$REPO' -> $VERCEL_PROJECT_ID"

  # Back-fill the repo variable so later runs skip the lookup (best-effort —
  # needs variables/administration write on this repo).
  if [ -n "${GH_ADMIN_TOKEN:-}" ] && [ -n "${GITHUB_REPOSITORY:-}" ]; then
    curl -sf -X POST -H "Authorization: Bearer $GH_ADMIN_TOKEN" \
      "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/variables" \
      -d "{\"name\":\"VERCEL_PROJECT_ID\",\"value\":\"$VERCEL_PROJECT_ID\"}" > /dev/null \
    || curl -sf -X PATCH -H "Authorization: Bearer $GH_ADMIN_TOKEN" \
      "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/variables/VERCEL_PROJECT_ID" \
      -d "{\"value\":\"$VERCEL_PROJECT_ID\"}" > /dev/null \
    || echo "::warning::could not persist VERCEL_PROJECT_ID repo variable — will re-resolve next run"
  fi
fi

echo "project_id=$VERCEL_PROJECT_ID" >> "$GITHUB_OUTPUT"
