name: ReleaseTest
on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  release:
    uses: progmise/reusable-workflows/.github/workflows/release-min.yml@debug/release-min
    secrets: inherit
